### ISSUE TITLE
Add cleaner way of checking posted JSON body

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#128]
Right now, you can check posted JSON body both on [JSONPath](https://github.com/dukeofharen/httplaceholder/blob/master/docs/CONDITIONS.md#jsonpath) and [plain request body](https://github.com/dukeofharen/httplaceholder/blob/master/docs/CONDITIONS.md#jsonpath) condition checkers. The JSONPath condition checker is a bit too verbose and the plain request body checker is perhaps a bit too simple for slightly more advanced scenarios.

It would be nice if there is a condition checker which would be somewhere in between. It would look like this:

```yaml
id: json-test
conditions:
  method: POST
  json:
    shouldBeInOrder: true # Default false
    cantContainExtraFields: true # Default false
    input:
      username: ^username$
      password: ^password$
      postedArray:
        - val1
        - val2
response:
  text: JSON IS OK!
```

The json condition checker has the properties `options` and `input`.

For `options` you will have `shouldBeInOrder`, which checks whether the posted JSON will be exactly in order as specified in the stub and `cantContainExtraFields` where you can specify whether extra fields in the posted JSON are allowed or not.

The `input` contains the actual JSON to check for. By default, the inserted string values will be checked as substring of the posted JSON, but you can also specify a regex. An array can also be specified.

In the above example, posting the following JSON will lead to a correct situation:

```json
{
    "username": "username",
    "password": "password",
    "postedArray": ["val1", "val2"]
}
```
