### ISSUE TITLE
Better way of specifying JSONPath condition

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#153]
Right now, a JSONPath expression is specified like this:

```yml
- id: jpath-test
  conditions:
    method: PUT
    url:
      path: /users
    jsonPath:
      - "$.phoneNumbers[?(@.type=='iPhone')]"
  response:
    statusCode: 204
```

Specifying a JSONPath like this combined with the expected type is in some cases hard to read and can beerror prone. Specifying a separate query and expected value is a better way.

It could be something like this:

```yml
- id: jpath-test
  conditions:
    method: PUT
    url:
      path: /users
    jsonPath:
      - query: $.phoneNumbers[0].type
        expectedValue: iPhone
  response:
    statusCode: 204
```

And can also be combined:
```yml
- id: jpath-test
  conditions:
    method: PUT
    url:
      path: /users
    jsonPath:
      - query: $.phoneNumbers[0].type
        expectedValue: iPhone
      - "$.phoneNumbers[?(@.type=='home')]"
  response:
    statusCode: 204
```

Because of backwards compatability reasons, both ways should be supported.
