### ISSUE TITLE
feat: Add variable handler for JSONPath

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#173]
# Feature Request

**Describe the Feature Request**

In some cases, you want to use a value that is posted in the JSON body as a value in the response. A JSONPath variable handler should be created for this purpose.

**Describe Preferred Solution**

Given the following stub:

```yaml
id: jsonpath-variable-parser
conditions:
  method: POST
  url:
    path: /jsonpath-variable-parser
response:
  enableDynamicMode: true
  text: 'Parsed value from JSON: ((jsonpath:$.values[1].title))'
```

When the following JSON is posted:

```json
{
    "values": [
        {
            "title": "Value1"
        },
        {
            "title": "Value2"
        }
    ]
}
```

Then we expect the following response body:

`Parsed value from JSON: Value2`

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_
