### ISSUE TITLE
feat: Implement stateful behavior

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#178]
# Feature Request

**Describe the Feature Request**

Wiremock supports stateful behavior (http://wiremock.org/docs/stateful-behaviour/). It does so by having the ability to attach a scenario to a stub. Whenever the stub is hit, the state of the scenario can be changed to a new value and another stub can be added that is only activated whenever that specific state is active. HttPlaceholder also should have this functionality.

**Describe Preferred Solution**

- Like with Wiremock, it should be possible to place a stub under a scenario.
- A scenario can have the following properties: a state (a simple string, beginning with "Start" which is the default value) and the number of times a scenario has been hit.
- The scenario state should be saved in memory and not on disk or in DB.

**Setting and checking state**

```
- id: stub-in-first-state
  scenario: test-scenario
  conditions:
    # Value "Start" is optional, because this is the default value
    scenario:
      scenarioState: Start
    url:
      path: /test-scenario
  response:
    # This will be the new state for scenario "test-scenario"
    scenario:
      setScenarioState: NewState
    text: Ok from initial state

- id: stub-in-new-state
  scenario: test-scenario
  conditions:
    scenario:
      scenarioState: NewState
    url:
      path: /test-scenario
  response:
    # Specifying this will make sure the state of the scenario will be put to "Start" again. Also, the number of scenario hits will be reset to "0".
    scenario:
      clearState: true
    text: Ok from new state
```

**Counting scenario hits**

```
- id: stub-with-zero-hits
  scenario: count-scenario
  conditions:
    scenario:
      exactHits: 0
    url:
      path: /count-scenario
  response:
    text: Ok with zero hits

- id: stub-with-one-hit
  scenario: count-scenario
  conditions:
    scenario:
      exactHits: 1
    url:
      path: /count-scenario
  response:
    scenario:
      clearState: true
    text: Ok with one hit

- id: stub-with-two-hits
  scenario: count-scenario
  conditions:
    scenario:
      exactHits: 2
    url:
      path: /count-scenario
  response:
    scenario:
      clearState: true
    text: Ok with two hit
```

These are the new stub options:
- scenario: the scenario the stub will operate under.
- scenarioState: a condition for specifying the state the scenario should be under.
- exactHits: a condition for specifying the exact number of hits the scenario should have.
- minHits: a condition for specifying the minimal inclusive hits a scenario should have.
- maxHits: a condition for specifying the maximum exclusive hits a scenario should have.
- setScenarioState: a response writer for setting the scenario state.
- clearState: a response writer for clearing the scenario state and the hit counter.

A few new endpoints should be added:
- An endpoint to request the state of all known scenario's.
- An endpoint to request the state of a specific scenario.
- An endpoint to set the state of a specific scenario.
- An endpoint to clear the state of a specific scenario.
- An endpoint to clear the states of all scenario's.

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_
