### ISSUE TITLE
feat: Add variable parser for inserting root URL in response

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#241]
# Feature Request

**Describe the Feature Request**

Right now, there is a variable handler for inserting the "display URL" in a response. This is the URL + path and query string. There should also be a "root URL variable handler", so that only the root URL (so without path + query string) will be inserted in the response.

**Describe Preferred Solution**

A stub with the new variable handler will look like this:

```yaml
id: dynamic-root-url-example
conditions:
  method: GET
  url:
    path: /dynamic-root-url.txt
response:
  enableDynamicMode: true
  text: 'URL: ((root_url))'
  headers:
    X-Header: ((root_url))
priority: 0
```

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_
