### ISSUE TITLE
feat: More string checker options

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#257]
# Feature Request

**Describe the Feature Request**

As can be read [here](https://github.com/dukeofharen/httplaceholder/blob/master/docs/docs.md#string-checking-keywords), there are multiple ways to check string contents. It would be nice to have a few extra checkers.

**Describe Preferred Solution**

The following string checkers would be nice to have (for example, we use `path`, but can be used for any checker that uses the string checking keywords as specified in the docs above):

_minLength_

The string to check should have a minimum (inclusive) length. Example:

```yml
- id: path-check
  conditions:
    url:
      path:
        minLength: 10 # Path should be at least 10 characters long.
  response:
    text: OK
```

_maxLength_

The string to check should have a maximum (inclusive) length. Example:

```yml
- id: path-check
  conditions:
    url:
      path:
        maxLength: 10 # Path should be at most 10 characters long.
  response:
    text: OK
```

_exactLength_

The string to check should have an exact (inclusive) length. Example:

```yml
- id: path-check
  conditions:
    url:
      path:
        exactLength: 10 # Path should be exactly 10 characters long.
  response:
    text: OK
```

_Other_

The checkers can also be combined.

```yml
- id: path-check
  conditions:
    url:
      path:
        minLength: 10
        maxLength: 15
  response:
    text: OK
```

In this case, the path should be at least 10 characters long and at most 15 characters long.

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_
