### ISSUE TITLE
feat: Add response option to return "connection reset"

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#258]
# Feature Request

**Describe the Feature Request**

In some situations, it might be nice to simulate a "connection reset" to simulate a network disturbance.

**Describe Preferred Solution**

Here is an example of how something like this might look like:

```yml
- id: connection-reset
  conditions:
    method: GET
    url:
      path:
        equals: /connection-reset
  response:
    abortConnection: true
```

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_
