### ISSUE TITLE
feat: Extra duration with a min and max duration

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#260]
# Feature Request

**Describe the Feature Request**

As can be read [here](https://github.com/dukeofharen/httplaceholder/blob/master/docs/docs.md#extra-duration), it is possible to delay the response with an x amount of milliseconds before returning it, to simulate a slow connection. It would be nice to also provide a min and a max number of milliseconds. This way, HttPlaceholder will pick a random number in between these 2 numbers. HttPlaceholder will wait this amount of milliseconds longer before returning the response.

**Describe Preferred Solution**

Here is an example of how this might look like:

```yml
- id: slow
  conditions:
    method: GET
    url:
      path:
        equals: /slooooow
  response:
    text: This was very slow.
    extraDuration:
      min: 20000
      max: 40000
```

Make sure to:
- update the OpenAPI definition of the `extraDuration`.
- update the stub validator so `min` can not be larger than / equal to `max`.

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_
