### ISSUE TITLE
feat: Allow "method" condition checker to support multiple keywords

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#298]
# Feature Request

**Describe the Feature Request**

Right now, the `method` condition checker can only contain one method at a time. It might be useful to be able to support multiple methods.

**Describe Preferred Solution**

_Stub with one method_

```yml
id: single-method
conditions:
  method: GET
response:
  statusCode: 200
  text: OK
```

_Stub with multiple methods: method should be one of the methods in the list_

```yml
id: multipe-methods
conditions:
  method:
    - GET
    - POST
response:
  statusCode: 200
  text: OK
```
