### ISSUE TITLE
feat: Define JSON response as object

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#375]
See https://httplaceholder.org/docs/#json-response. Right now, when defining a JSON response, it is always a string. It would be nice to also be able to define an object in YAML format. This way, it is a lot easier to define JSON because then you can define string values without having to escape them.

Example:

```yaml
- id: situation-json
  conditions:
    method: GET
    url:
      path:
        equals: /text.json
  response:
    statusCode: 200
    json:
      msg: 'All OK!'
```
