### ISSUE TITLE
bug: Calling multiple "((fake_data:words))" (or maybe other response variable parsers as well) are replaced with same value

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#377]
Example:

```yml
- id: get-news
  description: Returns news item for the news slider.
  conditions:
    method: GET
    url:
      path:
        equals: /api/v1/news
  response:
    enableDynamicMode: true
    json: |
      [
        {
          "title": "((fake_data:words))"
        },
        {
          "title": "((fake_data:words))"
        },
        {
          "title": "((fake_data:words))"
        },
        {
          "title": "((fake_data:words))"
        },
        {
          "title": "((fake_data:words))"
        }
      ]
```
