### ISSUE TITLE
feat: Add possibility to provide a JSON array and make it possible to return 1 item, all items, a selection of items or a random item from it

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#386]
# Feature Request

**Describe the Feature Request**

Add possibility to provide a JSON array and make it possible to return 1 item, all items, a selection of items or a random item from it. This way, it is much easier to mock / create a simple API without having to specify all separate responses as stubs.

**Describe Preferred Solution**

A stub with a mocked API might be created like this:

```yaml
id: facts-api
conditions:
  path:
    startswith: /facts
response:
  statusCode: 200
  # The base data will be added to the `json` response, but can also be added as `file` (e.g. to reuse the JSON data)
  json: |
    [
      {
        "id": 1,
        "fact": "The Grand Theft Auto franchise has lawsuits that total over $1 billion.",
      },
      {
        "id": 2,
        "fact": "Bangkok is the world’s most visited city."
      }
    ]
  jsonApi:
    enabled: true # Whether to enable the "JSON API" response writer.
    random: true # Whether to return a random item. If set to `false`, all items will be returned instead. Defaults to `false`.
    idKey: id # The JSON property that contains the ID. In this case, URL `/facts/1` will specifically search for a JSON entry with the specified ID and return that item. If no item is found, 404 is returned. This property is, by default, set to "id".
```
