### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by RemcoVisserVitas** [dukeofharen/httplaceholder#388]
# Feature Request

**Describe the Feature Request**

Validator for Querystring parameter containing multiple values

**Describe Preferred Solution**

In the request conditions I would like to be able to check if a querystring parameter contains multiple specific values.

For example if a request has the following querystring ?param1=a&param1=b

I would like to be able to to add a condition on querystring that param1 has both the values 'a' and 'b'. 

**Describe Alternatives**

An alternative could be something like 
query:
  param1:
    containsci: a,b

a comma separated list of values.

**Related Code**
```
-id: my stub
 conditions:
  url:
    query:
      param1:
        containsci:
          - a
          - b   
```

**Additional Context**

na
