### ISSUE TITLE
Add possibility to provide a parent for a stub

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#39]
Right now, if you have multiple stubs with the same conditions / response variables, you'll have to copy/paste those variables to the stubs. Let's take a look at the following example:

```yaml
- id: stub1
  conditions:
    url:
      path: /stub1
    method: GET
  response:
    headers:
      CustomHeader1: value
      Header1: value1
      Header2: value2
      Header3: value3
    text: OK1

- id: stub2
  conditions:
    url:
      path: /stub2
    method: GET
  response:
    headers:
      CustomHeader2: value
      Header1: value1
      Header2: value2
      Header3: value3
    text: OK2

- id: stub3
  conditions:
    url:
      path: /stub3
    method: GET
  response:
    headers:
      CustomHeader3: value
      Header1: value1
      Header2: value2
      Header3: value3
    text: OK3
```

Here you have 3 stubs with the same method condition and the same response headers. It would be nice if you could provide a parent where the method condition and response headers are set. This parent can then be set on the stubs. This might look something like this:

```yaml
- id: stub-parent
  conditions:
    method: GET
  response:
    headers:
      Header1: value1
      Header2: value2
      Header3: value3

- id: stub1
  parent: stub-parent
  conditions:
    url:
      path: /stub1
  response:
    headers:
      CustomHeader1: value
    text: OK1

- id: stub2
  parent: stub-parent
  conditions:
    url:
      path: /stub2
  response:
    headers:
      CustomHeader2: value
    text: OK2

- id: stub3
  parent: stub-parent
  conditions:
    url:
      path: /stub3
  response:
    headers:
      CustomHeader3: value
    text: OK3
```

In this case, the method condition and response headers are set on the stub `stub-parent` and the other stubs take that as parent. If you want to override a specific value, you can. The values defined in the child stub are always the truth.

The parent stub should **not** be taken into account when determining a stub to execute though.
