### ISSUE TITLE
Add response writer for content-type header

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#64]
Instead of specifying the `Content-Type` header for every request, introduce a specific response writer to do this instead. This is a nice shorthand notation.

A stub with the new response writer might look like this:

```yaml
- id: csv
  conditions:
    method: GET
    url:
      path: /result.csv
  response:
    statusCode: 200
    text: 'id,name,amount\n1,DukeOfHaren,20'
    contentType: text/csv
```
