### ISSUE TITLE
Variable parser for parsing XML with XPath and adding it to response

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#65]
Add more flexibility to a stub by providing a variable parser which parses (valid) XML, queries that XML using XPath and replacing the variable in the response with the result of the XPath query. Also take XML namespaces in account; this doesn't really work that well in .NET. Here is a possible example:

**The stub**
```yaml
- id: xpath-example
  conditions:
    method: POST
    url:
      path: /xpath-example
    xpath:
      - queryString: /soap:Envelope/soap:Body/m:GetStockPrice/m:StockName[text() = 'GOOG']
        namespaces:
          soap: http://www.w3.org/2003/05/soap-envelope
          m: http://www.example.org/stock/Reddy
  response:
    statusCode: 200
    text: The result: ((xpath_query:))
```

**The request**
```
POST http://localhost:5000/xpath-example
Content-Type: text/xml
<test>
    <body>
        <id>114</id>
        <name>Test XML string</name>
    </body>
</test>
```

**The response text**
`The result: 114`
