### ISSUE TITLE
Variable parser for parsing JSON with JSONPath and adding it to response

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#66]
Add more flexibility to a stub by providing a variable parser which parses (valid) JSON, queries that JSON using JSONPath and replacing the variable in the response with the result of the JSONPath query. Here is a possible example:

**The stub**
```yaml
- id: jsonpath-example
  conditions:
    method: POST
    url:
      path: /jsonpath-example
  response:
    statusCode: 200
    text: The result: ((jsonpath_query:$.phoneNumbers[?(@.type=='iPhone')].number))
```

**The request**
```
POST http://localhost:5000/jsonpath-example
Content-Type: application/json
{
  "firstName": "John",
  "lastName" : "doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}
```

**The response text**
`The result: 0123-4567-8888`
