### ISSUE TITLE
Variable parser for HttPlaceholder root URL

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#67]
Add a variable handler for inserting the HttPlaceholder root URL in the response. Here is a possible example:

**The stub**
```yaml
id: root-url-stub
conditions:
  method: GET
  url:
    path: /root-url
response:
  html: <html>((root_url))/sub/path</html>
```

**The request**
```
GET http://localhost:5000/root-url
```

**The response**
`<html>http://localhost:5000/sub/path</html>`
