### ISSUE TITLE
Make it possible to add a folder with static resources to a .yml file

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#83]
This might be handy for serving some static files from HttPlaceholder. It might look like this:

**The folder**
- static_files
-- img1.jpg
-- img2.jpg
-- subfiles
--- img3.jpg

**The stub**
```yaml
- id: static-files
  conditions:
    url:
      path: /static-files
  response:
    staticFilesDir: /home/user/static_files
```

**The request**
`GET http://localhost:5000/static-files/subfiles/img3.jpg`

**The response**
The file `img3.jpg`.
