### ISSUE TITLE
Condition checker based on date/time

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#86]
Create a condition checker for checking the date time. You need to be able to select UTC/local datetime, the from date/time and to date/time.
If type is not selected, the time will be considered as "local". At least from or to has to be set and can also be set both.

It might look like this:

```yaml
- id: datetime
  conditions:
    url:
      path: /datetime
    datetime:
      type: utc
      from: 2020-12-24 18:00:00
      to: 2021-01-01 01:00:00
  response:
    text: Happy holidays!
```
