### ISSUE TITLE
Cookie response writer

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#93]
Create a response writer for HTTP cookies. It might look something like this:

```yaml
- id: cookie-test
  conditions:
    method: GET
    url:
      path: /cookie-test
  response:
    cookie:
      key: id
      value: 1122
      expires: 2021-01-01 00:00:00 # Optional, will be formatted by HttPlaceholder in the correct way
      secure: true # Optional
      httpOnly: true # Optional
      path: /subpath # Optional
      sameSite: strict # Optional: can be "lax", "strict" or "none"
      domain: localhost:5000 # Optional
    text: OK Cookies!
```

In the example above, when you send a request to `http://localhost:5000/cookie-test`, a `Set-Cookie` header with the following value will be returned: `id=1122; Expires=Fri, 01 Jan 2021 00:00:00 GMT; Secure; HttpOnly; Path=/subpath; SameSite=strict; Domain=localhost:5000`

Cookie value can also contain a regex.
