### ISSUE TITLE
Cookie condition checker

### ISSUE THREAD

**Issue by dukeofharen** [dukeofharen/httplaceholder#94]
Make a simple condition checker to check the cookies in the `Cookie` header in the request. This might look something like this:

```yaml
- id: cookie-request-test
  conditions:
    cookie:
      - key: id
        value: 123
      - key: name
        value: (.*)
  response:
    text: OK cookie!
```

So, with the example above, the condition is correct if the following `Cookie` header is sent: `id=123; name=anyvalue`

Value can contain a regular string or a regex.
